# Generated by Django 2.0.8 on 2018-12-06 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asuntoCita', models.CharField(max_length=50, verbose_name='Asunto de la cita')),
                ('fechaCita', models.DateField(help_text='Formato: AAAA-MM-DD', verbose_name='Fecha de Cita')),
                ('horaCita', models.TimeField(verbose_name='Hora de Cita')),
                ('observacionCita', models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('Aplicada', 'Aplicada'), ('Pendiente', 'Pendiente'), ('No Asistio', 'No Asistio')], default=None, max_length=10)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fechaCita', 'horaCita'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDoctor', models.CharField(max_length=60, verbose_name='Nombre')),
                ('esDuenio', models.BooleanField(default=False, verbose_name=' Es la duenia? ')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['nombreDoctor'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('pagado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('observacionExp', models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['paciente'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresPaciente', models.CharField(max_length=60, verbose_name='Nombres del paciente')),
                ('apellidosPaciente', models.CharField(max_length=60)),
                ('ocupacion', models.CharField(blank=True, max_length=60, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=None, max_length=2)),
                ('fechaNacimiento', models.DateField(help_text='Formato: DD-MM-AAAA', verbose_name='Fecha de nacimiento')),
                ('direccionCasa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion Casa')),
                ('direccionTrabajo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion Trabajo')),
                ('telefonoCasa', models.CharField(blank=True, help_text='Formato: XXXX-XXXX', max_length=9, null=True, verbose_name='Telefono Casa')),
                ('telefonoTrabajo', models.CharField(blank=True, help_text='Formato: XXXX-XXXX', max_length=9, null=True, verbose_name='Telefono Trabajo')),
                ('referencia', models.CharField(blank=True, help_text='(En caso de ser niño)', max_length=60, null=True, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidosPaciente', 'nombresPaciente'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('nombresPaciente', 'apellidosPaciente')},
        ),
    ]
