# Generated by Django 2.0.6 on 2018-09-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='asuntoCita',
            field=models.CharField(max_length=50, verbose_name='Asunto de la cita'),
        ),
    ]
