# Generated by Django 2.0.8 on 2018-11-25 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0002_auto_20181125_2320'),
        ('GestionExpedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='odontograma',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odontograma.Odontograma'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='referencia',
            field=models.CharField(blank=True, help_text='(En caso de ser niño)', max_length=60, null=True, verbose_name='Responsable'),
        ),
    ]
