# Generated by Django 2.0.6 on 2018-06-28 21:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0003_auto_20180628_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='saldo',
        ),
        migrations.AddField(
            model_name='expediente',
            name='pagado1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='expediente',
            name='saldo1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
