# Generated by Django 2.0.6 on 2018-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0003_auto_20181127_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechaCita',
            field=models.DateField(help_text='Formato: AAAA-MM-DD', verbose_name='Fecha de Cita'),
        ),
    ]
