# Generated by Django 2.0.6 on 2018-12-06 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0004_auto_20181127_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
    ]
