# Generated by Django 2.0.8 on 2018-12-06 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0004_auto_20181127_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='pagado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
