# Generated by Django 2.0.6 on 2018-06-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0004_auto_20180628_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='pagado1',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='saldo1',
        ),
        migrations.AddField(
            model_name='expediente',
            name='pagado',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
    ]
