# Generated by Django 2.0.6 on 2018-06-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0005_auto_20180628_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
