# Generated by Django 2.0.6 on 2018-06-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0007_auto_20180628_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horaFinal',
            field=models.TimeField(null=True, verbose_name='Hora de Final'),
        ),
    ]
