# Generated by Django 2.0.6 on 2018-06-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0008_auto_20180628_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacionesconsulta',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='observacionesexpediente',
            name='expediente',
        ),
        migrations.AddField(
            model_name='expediente',
            name='oberservacionExp',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones'),
        ),
        migrations.DeleteModel(
            name='ObservacionesConsulta',
        ),
        migrations.DeleteModel(
            name='ObservacionesExpediente',
        ),
    ]
