# Generated by Django 2.0.6 on 2018-06-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0009_auto_20180628_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='oberservacionExp',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones'),
        ),
    ]
