# Generated by Django 2.0.6 on 2018-06-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0010_consulta_oberservacionexp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='oberservacionExp',
            new_name='observacionCons',
        ),
        migrations.RenameField(
            model_name='expediente',
            old_name='oberservacionExp',
            new_name='observacionExp',
        ),
    ]
