# Generated by Django 2.0.6 on 2018-06-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0011_auto_20180628_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='observacionCons',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='observacionExp',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones'),
        ),
    ]
