# Generated by Django 2.0.6 on 2018-09-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0012_auto_20180628_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(help_text='Formato: AAAA-MM-DD', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombresPaciente',
            field=models.CharField(max_length=60, verbose_name='Nombres del paciente'),
        ),
    ]
