# Generated by Django 2.0.6 on 2018-09-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0013_auto_20180927_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='observacionCita',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones'),
        ),
    ]
