# Generated by Django 2.0.6 on 2018-09-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0013_auto_20180926_0009'),
        ('GestionExpedientes', '0013_auto_20180925_1113'),
    ]

    operations = [
    ]
