# Generated by Django 2.0.6 on 2018-09-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0014_merge_20180926_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['nombreDoctor'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(help_text='Formato: DD-MM-AAAA', verbose_name='Fecha de nacimiento'),
        ),
    ]
