# Generated by Django 2.0.6 on 2018-09-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0015_auto_20180927_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Aplicada', 'Aplicada'), ('Pendiente', 'Pendiente'), ('No Asistio', 'No Asistio')], default=None, max_length=3),
        ),
    ]
