# Generated by Django 2.0.6 on 2018-09-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0015_auto_20180926_0119'),
        ('GestionExpedientes', '0013_auto_20180926_1526'),
    ]

    operations = [
    ]
