# Generated by Django 2.0.6 on 2018-09-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0017_auto_20180926_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='tratamientos',
        ),
    ]
