# Generated by Django 2.0.6 on 2018-09-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0018_remove_expediente_tratamientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
    ]
