# Generated by Django 2.0.6 on 2018-09-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0019_auto_20180926_2112'),
        ('odontograma', '0003_auto_20180926_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tratamiento',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
