# Generated by Django 2.0.6 on 2018-09-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0013_auto_20180924_1125'),
        ('GestionExpedientes', '0013_auto_20180927_1109'),
        ('GestionExpedientes', '0020_auto_20180926_2112'),
    ]

    operations = [
    ]
