# Generated by Django 2.0.6 on 2018-09-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0021_merge_20180928_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(help_text='Formato: DD-MM-AAAA', verbose_name='Fecha de nacimiento'),
        ),
    ]
