# Generated by Django 2.0.6 on 2018-09-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20180925_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='sex',
        ),
    ]
