# Generated by Django 2.0.6 on 2018-09-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_myuser_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='sex',
        ),
    ]
