# Generated by Django 2.0.8 on 2018-12-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionExpedientes', '0005_auto_20181206_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Expediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionExpedientes.Expediente')),
            ],
        ),
    ]
