# Generated by Django 2.0.6 on 2018-09-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionExpedientes', '0015_auto_20180926_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField()),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionExpedientes.Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionExpedientes.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza', models.IntegerField()),
                ('cara', models.CharField(choices=[('S', 'Vestibular'), ('C', 'Oclusal'), ('X', 'Pieza Completa'), ('Z', 'Distal'), ('D', 'Mesial'), ('I', 'Palatino')], max_length=4)),
                ('diagnostico', models.TextField()),
                ('notas', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('recomendado', 'Recomendado'), ('autorizado', 'Autorizado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='recomendado', max_length=12)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontograma.Odontograma')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionExpedientes.Tratamiento')),
            ],
        ),
    ]
