# Generated by Django 2.0.6 on 2018-09-27 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_created'),
            preserve_default=False,
        ),
    ]
