# Generated by Django 2.0.8 on 2018-11-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='odontograma',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='paciente',
        ),
    ]
