# Generated by Django 2.0.6 on 2018-12-06 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0002_auto_20181125_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fechaConsulta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Consulta'),
        ),
    ]
