# Generated by Django 2.0.6 on 2018-09-27 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionExpedientes', '0019_auto_20180926_2112'),
        ('odontograma', '0002_odontograma_fechacreacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaConsulta', models.DateField(auto_now_add=True, verbose_name='Fecha de Consulta')),
                ('horaInicio', models.TimeField(auto_now_add=True, verbose_name='Hora de inicio')),
                ('horaFinal', models.TimeField(null=True, verbose_name='Hora de Final')),
                ('observacionCons', models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestionExpedientes.Doctor')),
                ('odontograma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='odontograma.Odontograma')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestionExpedientes.Expediente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['fechaConsulta', 'horaInicio'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTratamiento', models.CharField(max_length=100, verbose_name='Nombre del tratamiento')),
                ('descripcionTratamiento', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripcion del tratamiento')),
                ('precioBase', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio Base')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['nombreTratamiento'],
            },
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontograma.Tratamiento'),
        ),
    ]
