# Generated by Django 2.0.6 on 2018-09-27 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0005_auto_20180926_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='odontograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontograma.Odontograma'),
        ),
    ]
