# Generated by Django 2.0.6 on 2018-09-28 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0006_auto_20180927_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='odontograma',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontograma.Odontograma'),
        ),
    ]
