# Generated by Django 2.0.6 on 2018-12-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odontograma', '0002_auto_20181125_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=45, verbose_name='Dosis')),
                ('duracion', models.CharField(max_length=45, verbose_name='Duracion')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(max_length=45, verbose_name='Nombre del medicamento')),
                ('marca_medicamento', models.CharField(max_length=45, verbose_name='Nombre del producto')),
                ('presentacion_medicamento', models.CharField(max_length=45, verbose_name='Nombre del producto')),
                ('form_farmaceutica', models.CharField(max_length=45, verbose_name='Nombre del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontograma.Consulta')),
                ('medicamento', models.ManyToManyField(through='recetas.Especificacion', to='recetas.Medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='especificacion',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.Medicamento'),
        ),
        migrations.AddField(
            model_name='especificacion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.Receta'),
        ),
    ]
